//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PharmacyId { get; set; }
        public Nullable<int> ManufactererId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> BestBeforeDateInYear { get; set; }
    
        public virtual Manufacterer Manufacterer { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
